name: Daily Prediction Update

on:
  schedule:
    - cron: '00 18 * * *'  # Runs daily at 23:30 IST (18:00 UTC)
  workflow_dispatch:       # Allows manual runs

jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository with LFS support
      uses: actions/checkout@v4
      with:
        lfs: false

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Chrome and Chromedriver
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable libnss3 libx11-xcb1 libgbm1 wget unzip
        CHROME_VERSION=$(google-chrome --version | awk '{print $3}')
        CHROMEDRIVER_URL="https://storage.googleapis.com/chrome-for-testing-public/$CHROME_VERSION/linux64/chromedriver-linux64.zip"
        wget -q "$CHROMEDRIVER_URL" -O chromedriver.zip
        unzip -o chromedriver.zip
        sudo mv -f chromedriver-linux64/chromedriver /usr/local/bin/chromedriver
        sudo chmod +x /usr/local/bin/chromedriver

    - name: Install Python packages
      run: |
        pip install --upgrade pip
        pip install --no-cache-dir -r requirements.txt

    - name: Download model
      run: |
        FILE_ID=1G46pHSZEY1UnG2YR8I2x7CX8IP6xlvGH
        FILE_NAME=model.pkl
        curl -c ./cookie -s -L "https://drive.google.com/uc?export=download&id=${FILE_ID}" > /tmp/intermediate.html
        CONFIRM_CODE=$(grep -o 'confirm=[^&]*' /tmp/intermediate.html | head -n 1 | cut -d= -f2)
        curl -Lb ./cookie "https://drive.google.com/uc?export=download&confirm=${CONFIRM_CODE}&id=${FILE_ID}" -o ${FILE_NAME}

    - name: Run prediction script
      run: python src/Electricity_Demand_Prediction.py

    - name: Pull latest changes before pushing
      run: |
        git fetch origin master
        git reset --soft origin/master  # ✅ Avoids conflicts by aligning history
        
    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add .
        git commit -m "Auto-update: New predictions $(date +'%Y-%m-%d')"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
