name: Daily Prediction Update

on:
  schedule:
    - cron: '30 18 * * *'  # Runs daily at 00:00 IST (18:30 UTC)
  workflow_dispatch:       # Allows manual runs

jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libnss3 libx11-xcb1 libgbm1

    - name: Install Python packages
      run: |
        pip install -r requirements.txt

    - name: Install Chrome and Driver
      run: |
        # Add Google Chrome repository
        sudo apt-get update
        sudo apt-get install -y wget unzip gnupg
        wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo gpg --dearmor -o /usr/share/keyrings/googlechrome-linux-keyring.gpg
        echo "deb [arch=amd64 signed-by=/usr/share/keyrings/googlechrome-linux-keyring.gpg] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
    
        # Install Chrome
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
    
        # Get ChromeDriver version
        CHROME_MAJOR=$(google-chrome --version | awk '{print $3}' | cut -d'.' -f1)
        CHROMEDRIVER_VERSION=$(wget -qO- "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_MAJOR")
        
        # Install ChromeDriver
        wget "https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip"
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin/
        sudo chmod +x /usr/local/bin/chromedriver
        rm chromedriver_linux64.zip

    - name: Verify installations
      run: |
        google-chrome --version
        chromedriver --version
        which chromedriver

    - name: Run prediction script
      run: |
        python src/Electricity_Demand_Prediction.py

    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add .
        git commit -m "Auto-update: New predictions $(date +'%Y-%m-%d')"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}