name: Daily Prediction Update

on:
  schedule:
    - cron: '30 18 * * *'  # Runs daily at 00:00 IST (18:30 UTC)
  workflow_dispatch:       # Allows manual runs

jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository with LFS support
      uses: actions/checkout@v4
      with:
        lfs: true  # ✅ Ensures LFS files are fetched

    - name: Install Git LFS and Fetch Large Files
      run: |
        git lfs install
        git lfs pull  # ✅ Downloads LFS-tracked files

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Chrome and dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable libnss3 libx11-xcb1 libgbm1 wget unzip

    - name: Install Python packages
      run: |
        pip install --upgrade pip
        pip install --no-cache-dir -r requirements.txt
        python -c "from webdriver_manager.chrome import ChromeDriverManager; ChromeDriverManager().install()"

    - name: Run prediction script
      run: python src/Electricity_Demand_Prediction.py

    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add .
        git commit -m "Auto-update: New predictions $(date +'%Y-%m-%d')"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
