name: Daily Prediction Update

on:
  schedule:
    - cron: '00 18 * * *'  # Runs daily at 23:30 IST (18:00 UTC)
  workflow_dispatch:       # Allows manual runs

jobs:
  update:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        lfs: false  # ✅ Ensures LFS files are fetched

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Install Chrome and Chromedriver
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable libnss3 libx11-xcb1 libgbm1 wget unzip
        CHROME_VERSION=$(google-chrome --version | awk '{print $3}')
        CHROMEDRIVER_URL="https://storage.googleapis.com/chrome-for-testing-public/$CHROME_VERSION/linux64/chromedriver-linux64.zip"
        wget -q "$CHROMEDRIVER_URL" -O chromedriver.zip
        unzip -o chromedriver.zip
        sudo mv -f chromedriver-linux64/chromedriver /usr/local/bin/chromedriver
        sudo chmod +x /usr/local/bin/chromedriver

    - name: Install Python packages
      run: |
        pip install --upgrade pip
        pip install --no-cache-dir -r requirements.txt

    - name: Run prediction script
      run: python src/Electricity_Demand_Prediction.py
      env:
        MONGODB_URI: ${{ secrets.MONGODB_URI }}  # Pass the secret to the script
        
    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git pull --rebase origin master  # Safer than reset
        git add .
        git commit -m "Auto-update: New predictions $(date +'%Y-%m-%d')"
        git push origin HEAD:master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
